### ISSUE TITLE
Object of type 'System.String' cannot be converted to type 'System.Int32'.

### ISSUE THREAD

**Issue by klanglie** [thepirat000/Audit.NET#177] opened 2018-11-11 14:03 UTC
Hello. My Identity Class uses AuditIdentityDbContext<ApplicationUser, ApplicationRole, string>. But when I go to seed my database, I get the below error. Is this because the systems expects ApplicationRole to use an integer id as a primary key? I really need to use a string for both ApplicationUser and ApplicationRole.. Other than inheriting from AuditIdentityDbContext, I don't think I am doing anything out of the ordinary.

Stack Trace:
`{System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Int32'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Audit.EntityFramework.Providers.EntityFrameworkDataProvider.CreateAuditEntity(Type definingType, Type auditType, EventEntry entry)
   at Audit.EntityFramework.Providers.EntityFrameworkDataProvider.InsertEventAsync(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEventAsync(Boolean forceInsert)
   at Audit.Core.AuditScope.SaveAsync()
   at Audit.EntityFramework.DbContextHelper.SaveScopeAsync(IAuditDbContext context, AuditScope scope, EntityFrameworkEvent event)
   at Audit.EntityFramework.DbContextHelper.SaveChangesAsync(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditIdentityDbContext`8.SaveChangesAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.SaveChanges(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.RoleStore`5.DeleteAsync(TRole role, CancellationToken cancellationToken)
`

**Comment by thepirat000** [comment] 2018-11-11 16:35
You should provide more information, like the code for configuring the audit output and mapping 

`Audit.Core.Configuration.UseEntityFramework(...)`

`Audit.EntityFrameowork.Configuration.Setup()...`

etc...

But from the stack trace I can see you are using the EF Provider and it looks like there is some property with the same name but distinct type between your audited entity and your audit entity. Did you created a new table to store the Role table audits? 

Check the mapping, try setting the [IgnoreMatchedProperties](https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#ef-provider-options) to true, but please provide more information to reproduce your issue.

**Comment by klanglie** [comment] 2018-11-11 19:53
Thanks for the prompt response. My setup looks similar to the example below. I am trying to use a single table to store all Audit records from all entities. That said, when ignoreMatchedProprties is false, this is when the error occurs. When I set it to true, it goes away. However, I am trying to understand the differentiation. By setting this property to true, am I missing out on seeing the older, previously stored values in my entities?

`	    var ignoreMatchedProperties = false;

            var auditLogOptionsBuilder = new DbContextOptionsBuilder<AuditLogDbContext>();
            auditLogOptionsBuilder.UseSqlServer(connectionString);

            CORE.Configuration.Setup()
                .UseEntityFramework(_ => _
                .UseDbContext<AuditLogDbContext>(auditLogOptionsBuilder.Options)
                .AuditTypeMapper(t => typeof(AuditRecord))
                .AuditEntityAction<AuditRecord>((ev, entry, entity) =>
                {
			// Process Here!
                }).IgnoreMatchedProperties(ignoreMatchedProperties));

            services.AddSingleton(CORE.Configuration.DataProvider);`

**Comment by thepirat000** [comment] 2018-11-11 20:10
By default, the library tries to set the properties with the same name on your `AuditRecord` with the values from the properties on your entity (i.e. `Role`).

So, if you don't need this behavior, or need to avoid it you can just set the `IgnoreMatchedProperties` to true. That means you must set the properties of your `AuditRecord` on the EntityActions

**Comment by klanglie** [comment] 2018-11-11 21:29
Makes perfect sense! Thanks, I appreciate your effort.

**Comment by klanglie** [comment] 2018-11-12 13:44
One small thing. I noticed in your example, you set .IgnoreMatchedProperties()) without passing in a variable. However, the default parameter is false so without passing in true it doesn't work. Thanks again!

**Comment by thepirat000** [comment] 2018-11-12 16:59
oh, nice catch... That's actually a bug, the default of the parameter should be true

**Comment by thepirat000** [comment] 2018-11-13 00:01
The default was fixed on new version 13.2.1

**Closed by thepirat000** 2018-11-13 00:01 UTC
