### ISSUE TITLE
Audit EF is saving an Inserted action when no insert actually happened.

### ISSUE THREAD

**Issue by VictorioBerra** [thepirat000/Audit.NET#200] opened 2019-02-05 20:19 UTC
Full reproduction: https://github.com/VictorioBerra/Audit.NET_EF_Issue200_RelatedEntitys

There are a few important things to note. One, is the automapper profile:

```csharp
cfg.CreateMap<CatUpdateViewModel, Cat>()
    .ForMember(dest => dest.CatBreedLine,
        opts => opts.MapFrom(src => src.CatBreedIds.Select(id => new CatBreedLine()
        {
            CatId = id,
            CatBreedId = src.Id
        })));
```

You can see, for every `CatUpdateViewModel` that I map to a Cat entity, it creates new instances of `CatBreedLine`.

Anyways, if you run the sample, look at the console output, **notice no second insert for a `CatBreedLine` happened, yet Audit.EF saves an Insert audit record!!**

![image](https://user-images.githubusercontent.com/2934507/52301775-da69cc80-2950-11e9-9581-fad317f4005a.png)

![image](https://user-images.githubusercontent.com/2934507/52301861-1866f080-2951-11e9-8e56-ecb835e38d96.png)

Also, I would like EF to NOT bump the Created*/Updated* stuff for the `CatBreedLine` too since the record didnt technically ever change...

**Comment by VictorioBerra** [comment] 2019-02-05 20:35
FYI Just pushed a slight bugfix to the AutoMapper profile. The issue still remains though.

That makes me wonder if auditing the line items is necessary? I am not sure how else I will know that an Update to a Cat changed the associated breed. You will see that even if you add a second breed and add on it, "Changes" never shows that. You can only see it in the entire Entity property on the JSON. So that means you would have to compare it yourself later.

**Comment by VictorioBerra** [comment] 2019-02-05 20:39
Also I am on Gitter, you can [@]me there if its easier.

**Comment by thepirat000** [comment] 2019-02-06 07:22
This is probably related to this issue https://github.com/thepirat000/Audit.NET/issues/78

The problem is the way the DbContext track the changes, The ChangeTracker is not able to track the state of independent associations (many-to-many relations). There was a fix for the non-core EF version to be able to include those relations, but I'm not sure if it's possible to do something similar for the EF Core version, 

Check [this](https://github.com/aspnet/EntityFrameworkCore/issues/1368) and [this](https://github.com/aspnet/EntityFrameworkCore/issues/10508).

**Comment by VictorioBerra** [comment] 2019-02-06 15:17
Yeah I suspected we were dealing with an EF Core issue.

EF sees the new object, so it considers it an insert, BUT since the primary key is set for the new object, it knows that it is an update and it generates an update statement.

![image](https://user-images.githubusercontent.com/2934507/52351094-a396c380-29ef-11e9-847e-9040055269f6.png)

Notice the update statement even though the Created* stuff only gets populated `if (entry.Action == "Insert")`.

Another workaround would be to send a flag from my UI saying if the entity is new or not. Then I can set the entity state and inform EF that its not something that needs to be added. But that's a ton of work for all my many-to-many tables. `[AuditIgnore]` is not a silver bullet because some many-to-many might have additional fields than just regular keys for associations. Like ProductOrderLine may have a Quantity field in addition to ProductId and OrderId for example.

**Comment by thepirat000** [comment] 2019-02-13 20:42
I'm closing this since it doesn't seem to be considered as an issue for EF, it's more a design decision and I don't think this behavior is going to change.

So for your case, you should probably `Include()` the `CatBreedLine` on the `Cat` retrieval and have some logic instead of the VM->Cat mapping that overrides the lines.

**Closed by thepirat000** 2019-02-13 20:42 UTC

**Comment by VictorioBerra** [comment] 2019-02-13 22:45
Unfortunately, my Cat example was a huge simplification of a much bigger project with many relationships and entities and generic repos 😬 so it wont be that easy. But i appreciate the advice.
