### ISSUE TITLE
Add-Migration Audit.Core.Configuration threw an exception. System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0

### ISSUE THREAD

**Issue by Tomazzzzz** [thepirat000/Audit.NET#216] opened 2019-05-08 07:33 UTC
Hello trying to Add-Migration with Fluen API  (project .net4.7.2)
`   Audit.Core.Configuration.Setup()
                .UseSqlServer(config => config
                    .ConnectionString(connectionName)
                    .Schema(dbType == DataBaseType.SqlServer ? "dbo" : "")
                    .TableName("Audit")
                    .IdColumnName("EventId")
                    .JsonColumnName("JsonData")
                    .LastUpdatedColumnName("LastUpdatedDate")
                    .CustomColumn("EventType", ev => ev.EventType)
                    .CustomColumn("User", ev => ev.Environment.UserName));
`
Getting the error:

> System.TypeInitializationException: The type initializer for 'Audit.Core.Configuration' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

I have 12.0.2 installed and added dependentAssembly to app.config file but still cannot add migration.
`  <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.2.0" newVersion="12.0.2.0" />
      </dependentAssembly>
`

THNX

**Comment by thepirat000** [comment] 2019-05-08 15:48
I was unable to reproduce. Even without the bindingRedirect it is not throwing the exception. Could you share the code for a minimal project that reproduces the problem?

**Comment by Tomazzzzz** [comment] 2019-05-09 07:00
It is a big project I hardly can isolate the code.
I can supply error log:

> PM> Add-Migration Audit -configuration SqlServerConfiguration
System.TypeInitializationException: The type initializer for 'Audit.Core.Configuration' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Audit.Core.Configuration..cctor()
   --- End of inner exception stack trace ---
   at Audit.Core.Configuration.Setup()
   at oProfits.DataAccessLayer.EntityFramework.Context.TemplateContext..ctor(String connectionName, DataBaseType dbType) in C:\Projects\OmniChannel\oProfits\OmniChannel\DataAccessLayer\DataBase\oProfits.DataAccessLayer.EntityFramework\Context\TemplateContext.cs:line 26
   at oProfits.DataAccessLayer.EntityFramework.Context.SqlServerContext..ctor() in C:\Projects\OmniChannel\oProfits\OmniChannel\DataAccessLayer\DataBase\oProfits.DataAccessLayer.EntityFramework\Context\SqlServerContext.cs:line 7
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Data.Entity.Infrastructure.DbContextInfo.CreateInstance()
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbProviderInfo modelProviderInfo, AppConfig config, DbConnectionInfo connectionInfo, Func`1 resolver)
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbConnectionInfo connectionInfo)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.RunCore()
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.Run()
The type initializer for 'Audit.Core.Configuration' threw an exception.

THNX

**Comment by thepirat000** [comment] 2019-05-09 16:44
still unable to reproduce. Next version of the library will include the update to newtonsoft.json 12.0.2

**Comment by thepirat000** [comment] 2019-05-09 17:52
Please upgrade to version 14.3.3 and try again

**Comment by thepirat000** [comment] 2019-05-14 15:35
I'm closing this assuming you fixed your assembly binding redirects or using the latest library version. Feel free to comment here if you're still having problems

**Closed by thepirat000** 2019-05-14 15:35 UTC

**Comment by Tomazzzzz** [comment] 2019-05-27 13:33
Hello now it is working with version 14.5.0. There is still a problem in Add-Migration.
Scaffolding creates empty migration. 
Where can I find tutorial where migration actually works.
THNX!!!
