### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by emdashsoftware** [thepirat000/Audit.NET#208] opened 2019-03-07 08:41 UTC
**Describe the bug**

**To Reproduce**
Steps or code to reproduce the behavior.

**Expected behavior**

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.WebApi: 13.0.0
 - Audit.EntityFramework: 13.0.0

**Additional context**

**Comment by emdashsoftware** [comment] 2019-03-07 09:13
**Description**
We are seeing intermittently the following exception thrown by our ASP.NET web application which uses Audit Entity Framework.  This is when saving a fairly large collection of entities.  

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
at EntityKeyHelper.GetColumnName(Type type, String propertyName, DbContext context)
at Audit.EntityFramework.DbContextHelper.GetColumnValues(IAuditDbContext context, DbEntityEntry entry)
at Audit.EntityFramework.DbContextHelper.CreateAuditEvent(IAuditDbContext context)
at Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
at Audit.EntityFramework.AuditDbContext.SaveChanges()
```

**To Reproduce**

We cannot consistently reproduce this error.

Resetting IIS on the web server resolves the issue when retrying the same operation.

**Libraries** 
We are using the following versions of Audit.NET

Audit.EntityFramework version="13.1.2" 
Audit.NET version="13.1.2"
EntityFramework version="6.1.3" 

**Additional Context**

This would seem to be a threading issue.  Having looked at the source code of the EntityKeyHelper class it seems that is uses ConcurrentDictionary almost everywhere except line 254:

new Dictionary<string, string>(); // **Not thread-safe, but not dangerous since at most it will lost some cached values**

Could this be causing the issue if _columnNamesCache is created as a Dictionary rather than ConcurrentDictionary ?

**Comment by thepirat000** [comment] 2019-03-07 19:32
I will evaluate adding some locking mechanism, however I was unable to reproduce the error even with an aggresive multi-threaded test.

**Comment by thepirat000** [comment] 2019-03-08 04:39
I'm still unable to reproduce the issue, but I've changed the inner dictionary to be `ConcurrentDictionary`, I guess the problem should go away. Please re-test with the latest package version (14.1.1)

**Comment by emdashsoftware** [comment] 2019-03-08 07:49
Hi Federico,

Thanks very much for the quick response and turnaround.  We will include the new build in our release and then monitor over the next couple of weeks or so,

Thanks,
  Dominic

___________________________________
Dominic Lawson
Development Manager
emdash Software Ltd
Email:    dominic@emdash.co.uk<mailto:dominic@emdash.co.uk>

emdash Software Ltd is the new name for CWJ Consulting Ltd.  Please update your address book with this new email address!

[signature_2111347051]

**Comment by thepirat000** [comment] 2019-03-08 16:51
Will close this for now. Feel free to comment here if you're still having problems

**Closed by thepirat000** 2019-03-08 16:51 UTC

**Comment by sdkumar25** [comment] 2020-02-13 12:42
Hi, I am getting the same error in my application when I save the audit event manually or automatically.
I am using Audit.Net and Audit.NET.MySql for logging the audit events. It's working fine when I run an application locally. But when I deploy the application in azure am getting **"System.IndexOutOfRangeException: Index was outside the bounds of the array"**
Please, help to resolve this issue.
