### ISSUE TITLE
I get a missing method Exception when saving

### ISSUE THREAD

**Issue by shubhamCedargate** [thepirat000/Audit.NET#599] opened 2023-04-25 03:36 UTC
**Describe the bug**
When I save a new record with Entity Framework I get an exception:

Message =  "Method not found: 'System.Threading.Tasks.Task`1<Audit.Core.IAuditScope> Audit.Core.IAuditScopeFactory.CreateAsync(Audit.Core.AuditScopeOptions)'."
 
 StackTrace =
 "   at Audit.EntityFramework.DbContextHelper.<CreateAuditScopeAsync>d__17.MoveNext()\r\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)\r\n   at Audit.EntityFramework.DbContextHelper.CreateAuditScopeAsync(IAuditDbContext context, EntityFrameworkEvent efEvent)\r\n   at Audit.EntityFramework.DbContextHelper.<SaveChangesGetAuditAsyncImpl>d__26.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Audit.EntityFramework.DbContextHelper.<SaveChangesAsync>d__23.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Cwm.DataLayer.CoreDbContext.<SaveChangesAsync>d__364.MoveNext() in C:\\SelfProjects\\cw\\src\\Cwm.DataLayer\\CoreDbContext.cs:line 238\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Cwm.Controllers.ApiV2.UserAuditsV2Controller.<Post>d__4.MoveNext() in C:\\SelfProjects\\cw\\src\\Cwm\\Controllers\\ApiV2\\UserAuditsV2Controller.cs:line 54\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()"

**To Reproduce**
In the Db context constructor:

        public CoreDbContext(IEncryption encryptionHelper, IUserSession userSession) :
            base(encryptionHelper, userSession)
        {
            _auditContext = new DefaultAuditContext(this);
            _helper.SetConfig(_auditContext);

            Audit.EntityFramework.Configuration.Setup()
            .ForAnyContext(_ => _
                .AuditEventType("EF")
                .IncludeEntityObjects())
            .UseOptOut();
            
            var esUri = new Uri("###ES URL here ###");
            var defaultIndex = "supresindex";
            var connectionSettings = new Nest.ConnectionSettings(esUri).DefaultIndex(defaultIndex);
            var auditDataProvider = new ElasticsearchDataProvider(new ElasticClient(connectionSettings));

            Audit.Core.Configuration.Setup()
                .UseCustomProvider(auditDataProvider);

            //Audit.Core.Configuration.Setup()
            //    .UseFileLogProvider(_ => _
            //        .Directory(@"C:\Logs\AuditLogs")
            //        .FilenameBuilder(ev => $"{ev.StartDate:yyyyMMddHHmmssffff}_{ev.EventType}.json"));
          }  
          
          
         In the overridden saveChanges method:
         
        public override async Task<int> SaveChangesAsync()
        {
            try
            {
                //return await _helper.SaveChangesAsync(_auditContext, () => base.SaveChangesAsync(acceptAllChangesOnSuccess, cancellationToken));
                return await _helper.SaveChangesAsync(_auditContext, () => base.SaveChangesAsync());

                //return await base.SaveChangesAsync();
            }
            catch (DbUpdateException ex)
            {
                throw HandleDbException(ex);
            }
        }
        
            
**Expected behavior**
I was getting the  audit logs as Json files initially :
            //Audit.Core.Configuration.Setup()
            //    .UseFileLogProvider(_ => _
            //        .Directory(@"C:\Logs\AuditLogs")
            //        .FilenameBuilder(ev => $"{ev.StartDate:yyyyMMddHHmmssffff}_{ev.EventType}.json"));
            
But I'm getting this exception after just installing the - Audit.NET.Elasticsearch package
          

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET, Version=21.0.0.0
 - Audit.NET.Elasticsearch, Version=21.0.0.0
 - Audit.EntityFramework, Version=20.2.4.0

**Target .NET framework:**
For example:
 - EntityFramework, Version=EntityFramework.6.4.4
 - .NET Framework 4.8

**Comment by thepirat000** [comment] 2023-04-25 05:37
You should call `Audit.Core.Configuration.Setup()` and `Audit.EntityFramework.Configuration.Setup()` **only once**, from your start-up or initialization code, since they set a global static configuration.

If you call them from your DbContext constructor, they will be called multiple times, potentially from different threads, overriding the global configuration each time and leading to errors.

So, you should move your Setup calls to your start-up code. 

An alternative to set the data provider per DbContext instance is to set the AuditDataProvider property of the IAuditDbContext in the constructor:

```c#
public CoreDbContext()
{
    _auditContext = new DefaultAuditContext(this);
    // Set the data provider for this DbContext instance: 
    _auditContext.AuditDataProvider = new FileDataProvider(c => c.Directory(@"C:\Logs"));
    _helper.SetConfig(_auditContext);
}
```

In this case, your DbContext will not use the globally configured data provider.

**Comment by shubhamCedargate** [comment] 2023-04-25 07:03
Yes sir,
The audit logs are generated when I add the mentioned code in the constructor:

`public CoreDbContext()
{
    _auditContext = new DefaultAuditContext(this);
    // Set the data provider for this DbContext instance: 
    _auditContext.AuditDataProvider = new FileDataProvider(c => c.Directory(@"C:\Logs"));
    _helper.SetConfig(_auditContext);
}`

But it stops working immediately after installing the `Audit.NET.Elasticsearch` package without any other code changes.

I need Audit.NET.Elasticsearch in order to write the audit logs onto ES.

**Comment by thepirat000** [comment] 2023-04-25 13:56
Can you share a sample project that reproduces the issue?

**Comment by thepirat000** [comment] 2023-04-28 03:06
Closing this assuming this was solved by correcting the version number. Otherwise please comment below

**Closed by thepirat000** 2023-04-28 03:06 UTC

**Comment by shubhamCedargate** [comment] 2023-04-28 03:17
I'm sorry for not replying. I created a sample application using .net4.8 and EF6 but could not replicate the issue. The exception disappeared after I did a fresh install of all the packages. Thank you for the assistance.

**Comment by shubhamCedargate** [comment] 2023-04-28 03:22
Also, what is the latest version of ES server that Audit.NET.Elasticsearch supports? https://cloud.elastic.co/ only allows the creation of an ES server of version 7.17.9 or higher for trial purposes. 

Audit.NET.Elasticsearch 21.0.0 installs the Elasticsearch.Net 7.17.0 package by default.

**Comment by thepirat000** [comment] 2023-04-28 03:28
> Also, what is the latest version of ES server that Audit.NET.Elasticsearch supports? https://cloud.elastic.co/ only allows the creation of an ES server of version 7.17.9 or higher for trial purposes.
> 
> Audit.NET.Elasticsearch 21.0.0 installs the Elasticsearch.Net 7.17.0 package by default.

You can force the use of 7.17.9 just adding the reference to that version on your app, assuming it will be binary compatible with 7.17.0+

**Comment by shubhamCedargate** [comment] 2023-05-10 16:06
Can we filter which entities to watch when using a custom data provider?

Previously, Did this using the Audit.EntityFramework; package by annotating the Entity with  [AuditInclude] :

 ` 
[AuditInclude]
public class Patient : EntityBase
`
and,  using .UseOptIn() to only track those entities

`
 Audit.EntityFramework.Configuration.Setup()
                .ForAnyContext(_ => _
                    .AuditEventType(EventTypeEntityFramework)
                    .IncludeEntityObjects())
                .UseOptIn();
`


Now, I'm trying to write logs into an ElasticSearch domain through Kinesis firehose, for which, I've created a custom data provider like this:

`
using Audit.Core;
using System;
using Amazon.KinesisFirehose;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using Amazon.KinesisFirehose.Model;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Threading;

namespace Cwm
{
    public class CustomKinesisFirehoseDataProvider : AuditDataProvider
    {
        private readonly AmazonKinesisFirehoseClient _kinesisFirehoseClient;
        private readonly string _deliveryStreamName;

        public CustomKinesisFirehoseDataProvider(AmazonKinesisFirehoseClient kinesisFirehoseClient, string deliveryStreamName)
        {
            _kinesisFirehoseClient = kinesisFirehoseClient;
            _deliveryStreamName = deliveryStreamName;
        }

        public override object InsertEvent(AuditEvent auditEvent)
        {
            var json = JsonConvert.SerializeObject(auditEvent, new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            var record = new Record { Data = new MemoryStream(Encoding.UTF8.GetBytes(json)) };
            var putRecordRequest = new PutRecordRequest
            {
                DeliveryStreamName = _deliveryStreamName,
                Record = record
            };

            _kinesisFirehoseClient.PutRecordAsync(putRecordRequest).Wait();

            return record;
        }

        public override async Task<object> InsertEventAsync(AuditEvent auditEvent, CancellationToken cancellationToken = default)
        {
            var json = JsonConvert.SerializeObject(auditEvent, new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            var record = new Record { Data = new MemoryStream(Encoding.UTF8.GetBytes(json)) };
            var putRecordRequest = new PutRecordRequest
            {
                DeliveryStreamName = _deliveryStreamName,
                Record = record
            };

            await _kinesisFirehoseClient.PutRecordAsync(putRecordRequest);

            return record;
        }


        public override void ReplaceEvent(object eventId, AuditEvent auditEvent)
        {
            var json = JsonConvert.SerializeObject(auditEvent, new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            var record = new Record { Data = new MemoryStream(Encoding.UTF8.GetBytes(json)) };
            var putRecordRequest = new PutRecordRequest
            {
                DeliveryStreamName = _deliveryStreamName,
                Record = record
            };

            _kinesisFirehoseClient.PutRecordAsync(putRecordRequest).Wait();

        }

        public override async Task ReplaceEventAsync(object eventId, AuditEvent auditEvent, CancellationToken cancellationToken = default)
        {
            var json = JsonConvert.SerializeObject(auditEvent, new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });

            var record = new Record { Data = new MemoryStream(Encoding.UTF8.GetBytes(json)) };
            var putRecordRequest = new PutRecordRequest
            {
                DeliveryStreamName = _deliveryStreamName,
                Record = record
            };

            await _kinesisFirehoseClient.PutRecordAsync(putRecordRequest);

        }

    }
}
`


and I've used this data provider in the Statrup config as such:

`
            var credentials = new BasicAWSCredentials("ACCESS_KEY", "SECRET_KEY");
            var kinesisFirehoseClient = new AmazonKinesisFirehoseClient(credentials, Amazon.RegionEndpoint.USEast1);
            var deliveryStreamName = "DATA_STREAM_NAME";
            var firehoseProvider = new CustomKinesisFirehoseDataProvider(kinesisFirehoseClient, deliveryStreamName);

            Audit.Core.Configuration.DataProviderFactory = () => firehoseProvider;

            Audit.Core.Configuration.Setup()
                .UseCustomProvider(firehoseProvider)
                .WithCreationPolicy(EventCreationPolicy.InsertOnStartInsertOnEnd);

            Audit.Core.Configuration.DataProvider = firehoseProvider;
`


I am able to write Audit logs into the Opensearch domain but am having a tough time configuring selective tracking of only certain entities like done previously.

Could you please point out if I'm missing something?
Thank You!

**Comment by shubhamCedargate** [comment] 2023-05-10 16:54
I missed changing the AuditOptionMode property of the annotation on the DbContext class.

Seems like it works after 

 [AuditDbContext(Mode = AuditOptionMode.OptIn, IncludeEntityObjects = false, AuditEventType = "EF")]
 internal class CoreDbContext : BaseContext<CoreDbContext>

**Comment by thepirat000** [comment] 2023-05-10 17:55
ok 👌

please note you don't need te following line:

```Audit.Core.Configuration.DataProviderFactory = () => firehoseProvider;```

since you're immediately calling .UseCustomProviser() whoch basically will do the same.
