### ISSUE TITLE
Mapping error illegal_argument_exception

### ISSUE THREAD

**Issue by cotepatrice** [thepirat000/Audit.NET#152] opened 2018-08-23 17:23 UTC
I have this mapping error message on some operations. In a particular controller, it happens on delete. It wants to map some text field to boolean and fails. 

`Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. ServerError: Type: illegal_argument_exception Reason: "mapper [entityFrameworkEvent.entries.changes.newValue] of different type, current_type [text], merged_type [boolean]"
   at Audit.Elasticsearch.Providers.ElasticsearchDataProvider.InsertEventAsync(AuditEvent auditEvent)
   at Audit.Core.AuditScope.SaveEventAsync(Boolean forceInsert)
   at Audit.Core.AuditScope.SaveAsync()
   at Audit.EntityFramework.DbContextHelper.SaveScopeAsync(IAuditDbContext context, AuditScope scope, EntityFrameworkEvent event)
   at Audit.EntityFramework.DbContextHelper.SaveChangesAsync(IAuditDbContext context, Func`1 baseSaveChanges)
   at Audit.EntityFramework.AuditDbContext.SaveChangesAsync(CancellationToken cancellationToken)
   at MyApi.Controllers.ClinicianController.DeleteClinicianAsync(Int32 clinicianId) in C:\dev\appbackend\src\MyApi\Controllers\ClinicianController.cs:line 186
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

But it logs perfectly on an insert operation in this same controller.

Version used 
 - Audit.EntityFramework.Core: 12.3.5
 - Audit.Net.Elasticsearch: 12.3.5
 - Elasticsearch docker image:  docker.elastic.co/elasticsearch/elasticsearch:6.3.1

API referencing Audit components is in a docker container while elasticsearch is on another one. 

It used to work well with older version of the elasticsearch image (6.2.4) and Audit components version 12.1.11.

**Comment by cotepatrice** [comment] 2018-08-23 17:51
`configurator.UseElasticsearch(config => config
                    .ConnectionSettings(new Uri(_options.ElasticSearchAddress))
                    .Index(_options.ElasticSearchIndex ?? "audit")
                    .Id(ev => Guid.NewGuid()));

Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
            {
                var httpContext = _httpContextAccessor.HttpContext;
                if (!httpContext.User.Identity.IsAuthenticated)
                {
                    return;
                }
                scope.SetCustomField("Auth0Id", httpContext.User.Identity.Name);
                scope.SetCustomField("SystemUserId", httpContext.User.FindFirstValue("SystemUserId"));
                scope.SetCustomField("UserRoles", httpContext.User.FindFirstValue("https://myapp.com/roles"));
            });
`

**Comment by cotepatrice** [comment] 2018-08-23 17:51
`configurator.UseElasticsearch(config => config
.ConnectionSettings(new Uri(_options.ElasticSearchAddress))
.Index(_options.ElasticSearchIndex ?? "audit")
.Id(ev => Guid.NewGuid()));

Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
var httpContext = _httpContextAccessor.HttpContext;
if (!httpContext.User.Identity.IsAuthenticated)
{
return;
}
scope.SetCustomField("Auth0Id", httpContext.User.Identity.Name);
scope.SetCustomField("SystemUserId", httpContext.User.FindFirstValue("SystemUserId"));
scope.SetCustomField("UserRoles", httpContext.User.FindFirstValue("https://myapp.com/roles"));
});`

**Comment by cotepatrice** [comment] 2018-08-23 17:56
After some tests, the pattern is : all the inserts works, all the updates and deletes fail with this error.

**Comment by thepirat000** [comment] 2018-08-23 20:28
Oh, I see what the problem is... 

Elasticsearch creates the [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) for the index when you insert documents to it, and the EntityFramework event has some fields that are dynamic "objects", like the Changes, ColumnValues, Entity and Primary Key. 

So for example, you could have an AuditEvent with `EntityFrameworkEvent.Entries[0].Changes[0].NewValue` as a Boolean, if you updated a boolean column on EF... But in a subsequent operation you could have the `NewValue` property as a Strin, and the operation will fail telling it is expecting a boolean value 👎... 

There is a workaround you can do with [Dynamic Templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html). 

You could create a dynamic mapping template as follows (assuming a local server for an index called "audit" and event type "auditevent"):

```
curl -X PUT \
  http://localhost:9200/audit/ \
  -d '{
  "mappings": {
    "auditevent": {
      "dynamic_templates": [
        {
          "pk": {
            "path_match": "*entityFrameworkEvent.entries.primaryKey.*",
            "mapping": {
              "type": "text"
            }
          }
        },
        {
          "changes": {
            "path_match": "*entityFrameworkEvent.entries.changes.*",
            "mapping": {
              "type": "text"
            }
          }
        },
        {
          "cols": {
            "path_match": "*entityFrameworkEvent.entries.columnValues.*",
            "mapping": {
              "type": "text"
            }
          }
        }
      ]
    }
  }
}'
```

This will treat the dynamic properties as strings and you should avoid the conflict.

**Comment by thepirat000** [comment] 2018-08-23 20:54
FYI

To quickly reproduce this, you can make the following inserts in a new index:

```
curl -X POST -H "content-type: application/json" -d "{ \"value\": true }" http://localhost:9200/tempindex/_doc
```

```
curl -X POST -H "content-type: application/json" -d "{ \"value\": \"some text\" }" http://localhost:9200/tempindex/_doc
```

The second insert fails because the "value" field is expected to be boolean.

**Comment by thepirat000** [comment] 2018-08-23 22:28
There is another way you can avoid this problem from client-side, and is making sure all the `object` properties of the audit event are serialized in the same way, for example as a JSON string.

For the EF event you could override the values in a custom action as follows:

```C#
Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
{
    foreach(var entry in scope.Event.GetEntityFrameworkEvent().Entries)
    {
        // Fix "Entity" property
        entry.Entity = ToJson(entry.Entity);
        // Fix Changes properties
        if (entry.Changes != null)
        {
            foreach (var change in entry.Changes)
            {
                change.NewValue = ToJson(change.NewValue);
                change.OriginalValue = ToJson(change.OriginalValue);
            }
        }
        // Fix ColumnValues properties
        if (entry.ColumnValues != null)
        {
            foreach (var colKey in entry.ColumnValues.Keys.ToList())
            {
                entry.ColumnValues[colKey] = ToJson(entry.ColumnValues[colKey]);
            }
        }
        // Fix Primary Key properties
        if (entry.PrimaryKey != null)
        {
            foreach (var pkKey in entry.PrimaryKey.Keys.ToList())
            {
                entry.PrimaryKey[pkKey] = ToJson(entry.PrimaryKey[pkKey]);
            }
        }
    }
});

private static string ToJson(object obj)
{
    return obj == null ? null : JsonConvert.SerializeObject(obj, Audit.Core.Configuration.JsonSettings);
}
```

**Comment by cotepatrice** [comment] 2018-08-24 13:01
I tried applying the template on your first solution (I only added the content type that is missing) but got a "resource_already_exists_exception".

```
100  1027  100   361  100   666  22562  41625 --:--:-- --:--:-- --:--:-- 64187{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [audit/JcYjIiD4Swy2UH7L0NKJGw] already exists","index_uuid":"JcYjIiD4Swy2UH7L0NKJGw","index":"audit"}],"type":"resource_already_exists_exception","reason":"index [audit/JcYjIiD4Swy2UH7L0NKJGw] already exists","index_uuid":"JcYjIiD4Swy2UH7L0NKJGw","index":"audit"},"status":400}

```

 I will try the custom action implementation now.

**Comment by thepirat000** [comment] 2018-08-24 16:26
Yes, you cannot change the existing mapping on elasticsearch indexes... I was assuming you were on a test environment and you could just delete the index and then re-create it with the mapping. But if that's not the case, I guess the only option you have is to re-index (https://www.elastic.co/blog/changing-mapping-with-zero-downtime).

**Comment by thepirat000** [comment] 2018-08-28 17:17
Hope that solves your issue, I'm closing this. If you are still having problems please reply to this.

**Closed by thepirat000** 2018-08-28 17:17 UTC

**Comment by xavieracostapolo** [comment] 2020-07-22 20:05
> There is another way you can avoid this problem from client-side, and is making sure all the `object` properties of the audit event are serialized in the same way, for example as a JSON string.
> 
> For the EF event you could override the values in a custom action as follows:
> 
> ```cs
> Audit.Core.Configuration.AddCustomAction(ActionType.OnEventSaving, scope =>
> {
>     foreach(var entry in scope.Event.GetEntityFrameworkEvent().Entries)
>     {
>         // Fix "Entity" property
>         entry.Entity = ToJson(entry.Entity);
>         // Fix Changes properties
>         if (entry.Changes != null)
>         {
>             foreach (var change in entry.Changes)
>             {
>                 change.NewValue = ToJson(change.NewValue);
>                 change.OriginalValue = ToJson(change.OriginalValue);
>             }
>         }
>         // Fix ColumnValues properties
>         if (entry.ColumnValues != null)
>         {
>             foreach (var colKey in entry.ColumnValues.Keys.ToList())
>             {
>                 entry.ColumnValues[colKey] = ToJson(entry.ColumnValues[colKey]);
>             }
>         }
>         // Fix Primary Key properties
>         if (entry.PrimaryKey != null)
>         {
>             foreach (var pkKey in entry.PrimaryKey.Keys.ToList())
>             {
>                 entry.PrimaryKey[pkKey] = ToJson(entry.PrimaryKey[pkKey]);
>             }
>         }
>     }
> });
> 
> private static string ToJson(object obj)
> {
>     return obj == null ? null : JsonConvert.SerializeObject(obj, Audit.Core.Configuration.JsonSettings);
> }
> ```
> 
> So you end up having records like:
> 
> ![image](https://user-images.githubusercontent.com/9836380/44555293-1d651a00-a6fa-11e8-9cbd-2184e54ba62d.png)

Este misma solucion me toco aplicar al momento de integrar EntityFramework con ElasticSearch, al momento de actualizar pasaba lo mismo, tengo mis dudas con el rendimiento de esto.
