### ISSUE TITLE
In-Memory Database

### ISSUE THREAD

**Issue by kevin-work** [thepirat000/Audit.NET#50] opened 2017-06-28 09:33 UTC
Does `Audit.EntityFramework` not work with in-memory database? I need it for testing. I am using EF Core with xUnit.

I have a context factory like so:

    public class DatabaseContextFactory
    {
        public DatabaseContext Create()
        {
            var serviceProvider = new ServiceCollection()
                .AddEntityFrameworkInMemoryDatabase()
                .BuildServiceProvider();

            var builder = new DbContextOptionsBuilder<DatabaseContext>();
            builder.UseInMemoryDatabase()
                .UseInternalServiceProvider(serviceProvider);

            return new DatabaseContext(builder.Options);
        }
    }

Where my `DatabaseContext` inherits from `AuditDbContext`:

    public sealed class DatabaseContext : AuditDbContext
    {
        public DatabaseContext(DbContextOptions options)
            : base(options)
        {
        }
    }

I get this error when running tests:

    System.IndexOutOfRangeException : Index was outside the bounds of the array.
    Stack Trace:
        at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
        at Audit.EntityFramework.DbContextHelper.EnsureEntitiesIncludeIgnoreAttrCache(Type type)
        at Audit.EntityFramework.DbContextHelper.IncludeEntity(IAuditDbContext context, EntityEntry entry,  AuditOptionMode mode)
        at Audit.EntityFramework.DbContextHelper.<>c__DisplayClass19_0.<GetModifiedEntries>b__0(EntityEntry x)
        at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
        at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
        at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
        at Audit.EntityFramework.DbContextHelper.GetModifiedEntries(IAuditDbContext context)
        at Audit.EntityFramework.DbContextHelper.CreateAuditEvent(IAuditDbContext context)
        at Audit.EntityFramework.DbContextHelper.SaveChanges(IAuditDbContext context, Func`1 baseSaveChanges)
        at Audit.EntityFramework.AuditDbContext.SaveChanges()

**Comment by kevin-work** [comment] 2017-06-28 10:04
After some more thinking it dawned on me that perhaps it was failing on saving the audit and not the entity itself (my original thought) and decided to stop it from saving audits while doing tests. So I added `Audit.Core.Configuration.DataProvider = new DynamicDataProvider();` to my database fixture class constructor so that it runs before tests. According to the documentation this stop "saving on the data provider" and my all my tests started working again.

**Comment by thepirat000** [comment] 2017-06-28 21:24
Are you using latest version of the packages?

Can you provide a more complete sample?

I was unable to reproduce. I've tested using an in-memory database and performing insert/update operations with no problems.

**Comment by thepirat000** [comment] 2017-06-28 21:38
Please try again targeting the latest version **>= 7.0.9**, the concurrency problem should be fixed now.

Feel free to re-open this issue if you are still having problems.

Regards

**Closed by thepirat000** 2017-06-28 21:38 UTC
