### ISSUE TITLE
Could not change name of id column for PostgreSQL

### ISSUE THREAD

**Issue by dietrichha** [thepirat000/Audit.NET#226] opened 2019-06-17 14:28 UTC
Everything worked great with Version 14.2.0 but starting with 14.2.2 I get an error while saving:

"id" column does not exists. The error is reported back from the PostgreSQL Database.

Init Code:
   Audit.Core.Configuration.DataProvider = new PostgreSqlDataProvider()
            {
                ConnectionString = Configuration.GetConnectionString("DefaultConnection"),
                IdColumnName = nameof(AuditEvent.ID),
                DataColumnName = nameof(AuditEvent.Data),
                TableName = nameof(AuditEvent),
                DataType = "JSONB"
            };

For me it looks like a default value for IdColumnName with the value "id" is used, instead of the passed value "ID". 

Greate work and thanks for your efforts!

**Comment by thepirat000** [comment] 2019-06-17 18:47
I think the problem is that "ID" is a [PostgreSQL reserved word](https://www.postgresql.org/docs/current/sql-keywords-appendix.html) and the Insert command is not double-quoting the column name. https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.PostgreSql/Providers/PostgreSqlDataProvider.cs#L257

I'll fix that soon and release a new version

**Comment by thepirat000** [comment] 2019-06-17 19:46
This was fixed on version 14.5.4, please update your references and try again

**Comment by dietrichha** [comment] 2019-06-18 10:40
After update, the error is gone. Everything works again. 
Thanks!

**Closed** 2019-06-19 04:44 UTC
