### ISSUE TITLE
Audit.NET.Elasticsearch: Throw "No route taking 1 parameters{index}/_create/{id}"

### ISSUE THREAD

**Issue by NEO-AFX** [thepirat000/Audit.NET#473] opened 2022-01-20 02:21 UTC
//
        // Summary:
        //     Specifies the Elasticsearch document Id to use for an audit event.
        //
        // Parameters:
        //   idBuilder:
        //     The builder to get the id to use for an audit event. NULL to use a server generated
        //     id.
        IElasticsearchProviderConfigurator Id(Func<Core.AuditEvent, Id> idBuilder);

Hello,if i set null to id at the Id function or not  execute Id function, will throw "No route taking 1 parameters{index}/_create/{id}".

**Comment by thepirat000** [comment] 2022-03-13 21:32
I see what the problem is: the library was using a `CreateRequest` (`/<target>/_create/<_id>`) instead of an `IndexRequest` (`/<target>/_doc/`) for the creation of the event. The former requires an ID to be passed and the latter does not.

I'm working on a fix for this. 

Sorry for the late response

**Comment by thepirat000** [comment] 2022-03-13 22:24
This was fixed on version 19.0.7, please upgrade your references and re-test

**Closed by thepirat000** 2022-03-13 22:24 UTC

**Comment by NEO-AFX** [comment] 2022-04-05 14:15
It works! Thank you!
